name: Deploy to VPS

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy on VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            set -e
            # Navigate to the backend directory
            cd /root/Auto-Certificate-Backend

            # Pull the latest changes from main branch
            git pull origin main

            # Rebuild only the fastapi service with the new code
            docker compose build fastapi

            # Restart the fastapi container (detached mode)
            docker compose up -d fastapi

            # Cleanup unused images to save disk space
            docker image prune -f
          EOF
